sudo: false
language: c

addons:
  apt_packages:
    - lib32stdc++6
    - lftp

env:
  - SOURCEMOD=1.8
  - SOURCEMOD=1.9
  - SOURCEMOD=1.10

matrix:
  fast_finish: true
  allow_failures:
    - env: SMVERSION=1.10

script:
  - bash build.sh $SOURCEMOD $B_FTP_HOST $B_FTP_USER $B_FTP_PASS 
