sudo: false
language: c

addons:
  apt_packages:
    - lib32stdc++6
    - lftp

env:
  - SOURCEMOD=1.7
  - SOURCEMOD=1.8
  - SOURCEMOD=1.9

matrix:
  fast_finish: true
  allow_failures:
    - env: SMVERSION=1.9

script:
  - bash build.sh $SOURCEMOD $B_FTP_HOST $B_FTP_USER $B_FTP_PASS 
